# Generated by Django 2.1.4 on 2018-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.BooleanField(default=True)),
                ('question_2', models.BooleanField(default=True)),
                ('question_3', models.BooleanField(default=True)),
                ('question_4', models.BooleanField(default=True)),
                ('question_5', models.BooleanField(default=True)),
                ('question_6', models.BooleanField(default=True)),
                ('answer', models.BooleanField(default=True, help_text='Answer is ')),
            ],
        ),
    ]
